name: logger
description: Small, easy to use and extensible logger which prints beautiful logs.
version: 1.1.1
homepage: https://github.com/leisim/logger

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.21.3
  flutter_lints: ^2.0.1
